params:
  red:
    name: "green"
    type: "continuous"
    low: 0.0
    high: 1.0
  yellow:
    name: "yellow"
    type: "continuous"
    low: 0.0
    high: 1.0
  blue:
    name: "blue"
    type: "continuous"
    low: 0.0
    high: 1.0
  green:
    name: "green"
    type: "continuous"
    low: null
    high: null
    set_wrt:
      - "red"
      - "green"
      - "blue"
objs:
  loss:
    name: "loss"
    type: "continuous"
    goal: "minimize"
general:
  batch_size: 1
  volume_prec: 0
  budget: 10
  timeout: 3600
  total_volume: 600.0  # uL
  grid_dims:
    rows: 4
    cols: 6
  target_hexcode: "#FFFF00"
  save_img_path: './run_imgs/'
protocol:
  name: "color_mixing"
  simulation: True  # wheter or not to simulate the opentrons protocol
  ot2_name: null  # ot2 name
  dest_path: '/data/user_storage/' # ot2 destination path with write permissions
  ot2_connection: "wireless"  # ot2 connection type: "wired" or "wireless"
  ot2_wired_ip: "169.254.121.85"  # ot2 wired (usb) address
  ot2_wireless_ip: "192.168.0.168" # ot2 wireless address

